services:
  - type: web
    name: auth-backend
    env: node
    region: oregon  # or change to your preferred region
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Optional: Render provides a port env var anyway
    pullRequestPreviewsEnabled: true
